import os
from llama_cpp import Llama
from core.runner.model.parser import Parser
from core.util.logger import Logger

class ModelResponse:
    message: str

    def __init__(self, message: str) -> None:
        self.message = message

    def __str__(self) -> str:
        return self.message

class RunnerConfig:
    context_window: int
    temp: float
    num_threads: int
    top_p:float
    model_name: str
    model_path: str
    llama_repo: str
    os: str
    pulpero_ready: bool
    response_size: int

    def __init__(self, context_window: int, temp: float, num_threads: int, top_p:float, model_name: str, model_path: str, llama_repo: str, os: str, pulpero_ready: bool, response_size: int) -> None:
        self.context_window = context_window
        self.temp= temp
        self.num_threads= num_threads
        self.top_p = top_p
        self.model_name = model_name
        self.model_path = model_path
        self.llama_repo = llama_repo
        self.os = os
        self.pulpero_ready = pulpero_ready
        self.response_size = response_size

    def __str__(self) -> str:
        return f'''
    context_window: {self.context_window}
    temp: {self.temp}
    num_threads: {self.num_threads}
    top_p: {self.top_p}
    model_name: {self.model_name}
    model_path: {self.model_path}
    llama_repo: {self.llama_repo}
    os: {self.os}
    pulpero_ready: {self.pulpero_ready}
    response_size: {self.response_size}
    '''

class Runner:

    def __init__(self, config: RunnerConfig, logger: Logger, parser: Parser) -> None:
        if config == None:
            raise ValueError("Model Runner config is nil")
        if logger == None:
            raise ValueError("Model Runner logger is nil")
        if parser == None:
            raise ValueError("Model Runner parser is nil")

        self.config = config
        self.logger = logger
        self.parser = parser
        self._initialize_model()

    def _initialize_model(self):
        try:
            model_path = self.config.model_path
            if not os.path.exists(model_path):
                raise FileNotFoundError(f"Model file not found: {model_path}")

            self.logger.debug(f"Initializing Llama ccp model from: {model_path}")
            self.llm = Llama(
                model_path=model_path,
                n_ctx=self.config.context_window,
                n_threads=self.config.num_threads,
                n_gpu_layers=14,  # Equivalent to -ngl 14
                n_batch=256,      # Equivalent to -b 256
                verbose=False,
                use_mmap=True,
                use_mlock=False,
                rope_scaling_type=None,
                rope_freq_base=10000.0,
                rope_freq_scale=1.0,
            )
            self.logger.debug("Llama ccp model initialized successfully")
        except Exception as e:
            self.logger.error(f"Failed to initialize Llama model: {e}")
            raise

    def run_local_model(self, tmp_prompt: str, config: RunnerConfig) -> ModelResponse:
        try:
            with open(tmp_prompt, 'r', encoding='utf-8') as f:
                prompt_content = f.read()

            self.logger.debug("Generating response with Llama ccp")

            response = self.llm(
                prompt_content,
                max_tokens=config.response_size,
                temperature=config.temp,
                top_p=config.top_p,
                repeat_penalty=1.15,
                stop=["User:", "\n\nUser:", "</s>"],
                echo=False
            )

            if not response or not response.get('choices'):
                self.logger.error("Command execution failed - no response")
                return ModelResponse("It's looks like there is a problem with the answer generated by the model, try with a different query.")

            generated_text = response['choices'][0]['text']
            self.logger.debug(f"Raw model response: {generated_text}")

            if not generated_text or generated_text.strip() == '':
                self.logger.error("The result is nil or empty")
                return ModelResponse("It's looks like there is a problem with the answer generated by the model, try with a different query.")

            return ModelResponse(generated_text)

        except Exception as e:
            self.logger.error(f"Error during model inference: {e}")
            return ModelResponse("An Error ocurred when we try to run infer the response")

    def talk_with_model(self, tmp_prompt: str) -> str:
        model_response: ModelResponse = self.run_local_model(tmp_prompt, self.config)
        return model_response.message

    def __del__(self):
        if hasattr(self, 'llm') and self.llm:
            del self.llm
