import os
from llama_cpp import Llama
from typing import Dict

class Runner:

    def __init__(self, config, logger, parser) -> None:
        if config == None:
            raise ValueError("Model Runner config is nil")
        if logger == None:
            raise ValueError("Model Runner logger is nil")
        if parser == None:
            raise ValueError("Model Runner parser is nil")

        self.config = config
        self.logger = logger
        self.parser = parser
        self._initialize_model()
        self.model_parameters = {
                "mirostat": "2",
                "context_window": self.config["context_window"],
                "response_size": "512",
                "temp": "0.1",
                "top_p": "0.3",
                "num_threads": self.config["num_threads"],
                "model_path": self.config["model_path"],
                "command_debug_output": self.logger.get_config()["command_path"]
        }

    def _initialize_model(self):
        try:
            model_path = self.config["model_path"]
            if not os.path.exists(model_path):
                raise FileNotFoundError(f"Model file not found: {model_path}")

            self.logger.debug(f"Initializing Llama model from: {model_path}")
            self.llm = Llama(
                model_path=model_path,
                n_ctx=int(self.config["context_window"]),
                n_threads=int(self.config["num_threads"]),
                n_gpu_layers=14,  # Equivalent to -ngl 14
                n_batch=256,      # Equivalent to -b 256
                verbose=False,
                use_mmap=True,
                use_mlock=False,
                rope_scaling_type=None,
                rope_freq_base=10000.0,
                rope_freq_scale=1.0,
            )
            self.logger.debug("Llama model initialized successfully")
        except Exception as e:
            self.logger.error(f"Failed to initialize Llama model: {str(e)}")
            raise

    def run_local_model(self, tmp_prompt: str, config: Dict) -> Dict[str, str]:
        try:
            with open(tmp_prompt, 'r', encoding='utf-8') as f:
                prompt_content = f.read()

            self.logger.debug("Generating response with Llama model")

            response = self.llm(
                prompt_content,
                max_tokens=int(config["response_size"]),
                temperature=float(config["temp"]),
                top_p=float(config["top_p"]),
                repeat_penalty=1.15,
                stop=["User:", "\n\nUser:", "</s>"],
                echo=False
            )

            if not response or not response.get('choices'):
                self.logger.error("Command execution failed - no response")
                return {"message": "It's looks like there is a problem with the answer generated by the model, try with a different query."}

            generated_text = response['choices'][0]['text']
            self.logger.debug(f"Command execution completed: {generated_text}")

            if not generated_text or generated_text.strip() == '':
                self.logger.error("The result is nil or empty")
                return {"message": "It's looks like there is a problem with the answer generated by the model, try with a different query."}

            parser_result = self.parser.clean_model_output(generated_text)
            return {"message": parser_result}

        except Exception as e:
            self.logger.error(f"Error during model inference: {str(e)}")
            return {"message": "An Error ocurred when we try to run infer the response"}

    def talk_with_model(self, tmp_prompt: str) -> str:
        model_response = self.run_local_model(tmp_prompt, self.model_parameters)
        return model_response["message"]

    def __del__(self):
        if hasattr(self, 'llm') and self.llm:
            del self.llm
