name: Create Core Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Core Bundle
        run: |
          cd lua/pulpero/core
          tar -czf core-bundle-${GITHUB_REF#refs/tags/v}.tar.gz ./*

      - name: Update Versions Manifest
        run: |
          sudo apt-get install jq
          FILENAME=core-bundle-${GITHUB_REF#refs/tags/v}.tar.gz
          CHECKSUM=$(shasum -a256 core-bundle-${GITHUB_REF#refs/tags/v}.tar.gz)
          VERSION=${GITHUB_REF#refs/tags/v}
          DATE=$(date)
          JSON_STRING=$( jq -n \
          --arg cs "$CHEckSUM" \
          --arg vs "$VERSION" \
          --arg fn "$FILENAME" \
          --arg dt "$DATE" \
          '{ version: $vs, url: "https://github.com/AgustinAllamanoCosta/pulpero/releases/download/$vs/$fn", checksum: $cs, releaseDate: $dt, minEditorVersion: "5.0.0", breaking: false}')
          NEW_VERSION=$(cat ./releases/version.json | jq '.versions[.versions | lenght] |= . + ${JSON_STRING}')
          rm ./releases/version.json
          echo $NEW_VERSION > ./releases/version.json

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            core-bundle-*.tar.gz
            versions.json
