name: Plugin Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install llama.cpp
        run: |
          git clone https://github.com/ggerganov/llama.cpp
          cd llama.cpp
          make LLAMA_OPENBLAS=1
          sudo cp llama /usr/local/bin/

      - name: Download TinyLlama
        run: |
          mkdir -p models
          wget --header="Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
          https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf \
          -O models/tinyllama.gguf

      - name: Run Tests
        run: |
          mkdir -p ~/.config/nvim
          cp -r . ~/.config/nvim/pack/plugins/start/autodoc.nvim
          nvim --headless -u test/minimal_init.lua -c "PlenaryBustedDirectory test/ { minimal_init = 'test/minimal_init.lua' }"
